default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  yaroslav
  password:  password

development:
  <<: *default
  database: yaroslav_development


test:
  <<: *default
  database: yaroslav_test

#   production:
#     url: <%= ENV['MY_APP_DATABASE_URL'] %>

production:
  <<: *default
  database: yaroslav_production
  username: yaroslav
  password: <%= ENV['YAROSLAV_DATABASE_PASSWORD'] %>
